### ISSUE TITLE
usage as a registry

### ISSUE THREAD

**Issue by mathisloge** [commschamp/cc.vcpkg#1]
Hey Alex, 

could we change the structure to be used with https://learn.microsoft.com/en-us/vcpkg/users/registries? 

I think at least a `version/baseline.json` is required. I would add it as a PR.

**Comment by arobenko** [comment]
Hi Mathis,
If you know what you're doing, you are more than welcome to introduce
changes. I'll appreciate it if you do it for all the supported packages.
Please submit your changes for the develop branch.

**Comment by mathisloge** [comment]
Fixed

**Comment by arobenko** [comment]
Officially [released](https://github.com/commschamp/cc.vcpkg/releases/tag/2023-08-27).

**Comment by mathisloge** [comment]
Thanks Alex
